Repository volta-cli/action, pull requests merged in 2022-08, with the labels that each got.

#89 Fix usage on Linux distributions other than Ubuntu (e.g. CentOS, RHEL, &c)
  src/installer.test.ts
  src/installer.ts
Labels: bug

#86 Update dependencies / devDependencies to latest
  package-lock.json
  package.json
Labels: internal

#91 Update action metadata to leverage Node 16
  action.yml
Labels: breaking

#75 Output ESM into dist/
  .eslintrc.cjs
  jest.config.js
  package.json
  tsconfig.json
Labels: breaking

#92 Migrate CI jobs to checkout `action` into subdirectory
  .github/workflows/CI.yml
Labels: internal

#93 Drop support for usage with Volta older than 1.0.0
  .github/workflows/CI.yml
  package-lock.json
  package.json
  src/installer.test.ts
  src/installer.ts
Labels: breaking

#95 Add `scope` to list of inputs
  action.yml
Labels: bug

#96 Prevent test harness from defaulting to `./action` as default working directory
  .github/workflows/CI.yml
Labels: internal

#46 Update to npm@8
  package-lock.json
  package.json
Labels: internal

#97 Use `${{ github.token }}` to authenticate tool cache downloads
  action.yml
  package.json
  src/index.ts
  src/installer.ts
Labels: enhancement

#98 Adding optional input for openssl-version
  action.yml
  src/index.ts
  src/installer.test.ts
  src/installer.ts
Labels: enhancement

#99 Update README to include current versions
  README.md
Labels: documentation
