Repository volta-cli/action, pull requests merged in 2022-09, with the labels that each got.

#101 Use GitHub API to retrieve latest release information.
  package-lock.json
  package.json
  src/installer.test.ts
  src/installer.ts
Labels: bug

#103 Remove reference to https://volta.sh/latest-version in logging
  src/installer.ts
Labels: documentation

#104 Add action-docs updater
  README.md
  package-lock.json
  package.json
Labels: documentation

#102 Replace `openssl-version` configuration with `variant`
  README.md
  action.yml
  src/index.ts
  src/installer.test.ts
  src/installer.ts
Labels: breaking

#105 Add CI scenario acceptance test using `variant`
  .github/workflows/CI.yml
Labels: internal

#106 Update devDependencies to latest
  package-lock.json
  package.json
Labels: internal

#107 Add `package-json-path` input to specify location of `package.json`
  .github/workflows/CI.yml
  action.yml
  package-lock.json
  package.json
  src/index.ts
  src/installer.ts
Labels: enhancement
